/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package com.test.gae.dto;

import com.spoledge.audao.db.dto.AbstractDto;

/**
 * This is a DTO class.
 *
 * @author generated
 */
public class SecurityQnA extends AbstractDto {

    ////////////////////////////////////////////////////////////////////////////
    // Static
    ////////////////////////////////////////////////////////////////////////////

    public static final String TABLE = "securityQnA";

    ////////////////////////////////////////////////////////////////////////////
    // Attributes
    ////////////////////////////////////////////////////////////////////////////

    private Long id;
    private String username;
    private String password;
    private String question;
    private String answer;

    ////////////////////////////////////////////////////////////////////////////
    // Constructors
    ////////////////////////////////////////////////////////////////////////////

    /**
     * Creates a new empty DTO.
     */
    public SecurityQnA() {
    }

    ////////////////////////////////////////////////////////////////////////////
    // Public
    ////////////////////////////////////////////////////////////////////////////

    public Long getId() {
        return id;
    }

    public void setId( Long _val) {
        this.id = _val;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername( String _val) {
        this.username = _val;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword( String _val) {
        this.password = _val;
    }

    public String getQuestion() {
        return question;
    }

    public void setQuestion( String _val) {
        this.question = _val;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer( String _val) {
        this.answer = _val;
    }

    /**
     * Indicates whether some other object is "equal to" this one.
     * Uses 'columns' equality type.
     */
    @Override
    public boolean equals( Object _other ) {
        if (_other == this) return true;
        if (_other == null || (!(_other instanceof SecurityQnA))) return false;

        SecurityQnA _o = (SecurityQnA) _other;

        if ( id == null ) {
            if ( _o.id != null ) return false;
        }
        else if ( _o.id == null || id.longValue() != _o.id.longValue()) return false;

        if ( username == null ) {
            if ( _o.username != null ) return false;
        }
        else if ( _o.username == null || !username.equals( _o.username )) return false;

        if ( password == null ) {
            if ( _o.password != null ) return false;
        }
        else if ( _o.password == null || !password.equals( _o.password )) return false;

        if ( question == null ) {
            if ( _o.question != null ) return false;
        }
        else if ( _o.question == null || !question.equals( _o.question )) return false;

        if ( answer == null ) {
            if ( _o.answer != null ) return false;
        }
        else if ( _o.answer == null || !answer.equals( _o.answer )) return false;

        return true;
    }

    /**
     * Returns a hash code value for the object.
     */
    @Override
    public int hashCode() {
        int _ret = -1077008828; // = "SecurityQnA".hashCode()
        _ret += id == null ? 0 : (int)(id ^ (id >>> 32));
        _ret = 29 * _ret + (username == null ? 0 : username.hashCode());
        _ret = 29 * _ret + (password == null ? 0 : password.hashCode());
        _ret = 29 * _ret + (question == null ? 0 : question.hashCode());
        _ret = 29 * _ret + (answer == null ? 0 : answer.hashCode());

        return _ret;
    }


    ////////////////////////////////////////////////////////////////////////////
    // Protected
    ////////////////////////////////////////////////////////////////////////////
		
    /**
     * Constructs the content for the toString() method.
     */
    protected void contentToString(StringBuffer sb) {
        append( sb, "id", id );
        append( sb, "username", username );
        append( sb, "password", password );
        append( sb, "question", question );
        append( sb, "answer", answer );
    }
}
