CREATE TABLE USER_ACCOUNTS_VIEW
(
   UA_NAME varchar(30) NOT NULL,
   DESCRIPTION varchar(100),
   DATE_CREATED date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

//INSERT INTO USER_ACCOUNTS_VIEW VALUES ('jen1','dummy account','2011-06-06')