/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package com.test.oracle.dao.oracle;

import java.sql.Connection;

import com.test.oracle.dao.*;


/**
 * This is the main implementation class for obtaining DAO objects.
 * @author generated
 */
public class DaoFactoryImpl extends DaoFactory.Factory {
    public UserSecurityQuestionDao createUserSecurityQuestionDao( Connection conn ) {
        return new UserSecurityQuestionDaoImpl( conn );
    }

}
